# Font configuration
[font]
  size = 11.0

  [font.normal]
    family = "JetBrainsMono Nerd Font"  # Specify the Nerd Font family
    style = "Regular"  # Specify the font style

# Window transparency
[window]
  opacity = 0.5

# Window padding
[window.padding]
  x = 15
  y = 15
